# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: ClassicOldSong
    url: https://ccoooss.com
  - name: Frantic1048
    url: https://frantic1048.logdown.com/
  - name: Hclmaster
    url: https://hclmaster.github.io/
  - name: WANG Hsü-Tung
    url: https://whst.github.io/

# navigation menu
menu:
  - name: HOME
    slug: home
    url: /
  - name: CSVTOJSON
    slug: csvtojson
    url: https://csv.keyangxiang.com
  - name: PSDETCH
    slug: psdetch
    url: https://psdetch.com
    target: _blank
  - name: UML Editor
    slug: uml_editor
    url: https://uml.keyangxiang.com
    target: _blank
  - name: ARCHIVES
    slug: archives
    url: /archives

# widgets
widgets:
  - about
  # - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/keyang
- slug: twitter
  url: https://twitter.com/keyangxiang
- slug: rss
	url: /atom.xml
